version: 2
jobs:
    node-10:
        docker:
            - image: circleci/node:10
        working_directory: ~/common-logger-test-suite
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn test
    node-11:
        docker:
            - image: circleci/node:11
        working_directory: ~/common-logger-test-suite
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn test
    node-12:
        docker:
            - image: circleci/node:12
        working_directory: ~/common-logger-test-suite
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn test
workflows:
    version: 2
    build_and_test:
        jobs:
            - node-10
            - node-11
            - node-12
